#import "./_Sections.gql"
#import "./_Location.gql"
#import "./_PostNavigation.gql"

fragment PostFragment on Post {
  id
  title
  subtitle
  publishDate
  published
  locations {
    ...LocationFragment
  }
  header {
    ratio
    id
    url
    width
    height
  }
  trip {
    title
    id
  }
  sections {
    ...SectionsFragment
  }
  ...PostNavigation
}
