fragment SectionsFragment on Section {
  ... on TextSection {
    id
    title
    body
    index
  }
  ... on PhotoRowSection {
    id
    index
    items {
      id
      index
      photo {
        id
        url
        ratio
        width
        height
      }
    }
  }
  ... on HeroSection {
    id
    index
    photo {
      id
      url
      ratio
    }
  }
}
