mutation($id: String!, $title: String, $subtitle: String, $startDate: Date, $endDate: Date) {
  updateTrip(id: $id, title: $title, subtitle: $subtitle, startDate: $startDate, endDate: $endDate) {
    id
    title
    subtitle
    startDate
    endDate
  }
}
