#import "./_Post.gql"

mutation($id: String!, $title: String, $subtitle: String, $startDate: Date, $endDate: Date, $published: Boolean) {
  updatePost(id: $id, title: $title, subtitle: $subtitle, startDate: $startDate, endDate: $endDate, published: $published) {
    ...PostFragment
  }
}
