mutation ($id: String!, $index: Int) {
  updateSection(id: $id, index: $index) {
    ... on TextSection {
      id
      index
    }
    ... on PhotoRowSection {
      id
      index
    }
    ... on HeroSection {
      id
      index
    }
  }
}
