#import "./_TripCard.gql"

query UserPageQuery($username: String!) {
  user(username: $username) {
    id
    name
    isViewer
    username
    trips {
      ...TripCardFragment
      viewerCanEdit
    }
  }
}
